name: Create release
on:
  push:
    tags:
      - "v*"

env:
  IMAGE: ghcr.io/${{ github.repository }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 5

      - name: Git tag sha
        id: src
        uses: docker/metadata-action@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          images: ${{ env.IMAGE }}
          flavor: latest=false
          tags: type=sha

      - name: Release tags
        id: meta
        uses: docker/metadata-action@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          images: ${{ env.IMAGE }}
          flavor: latest=false
          tags: |
            # {{version}} is major.minor.patch
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Tag and push image
        uses: akhilerm/tag-push-action@v2.2.0
        with:
          src: ${{ steps.src.outputs.tags }}
          dst: |
            ${{ steps.meta.outputs.tags }}

      - name: Publish Changelog to GitHub
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifactErrorsFailBuild: true
          generateReleaseNotes: true
          draft: true
          prerelease: true
          artifacts: "t"